apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cloudaware-node-readerU
rules:
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cloudaware-node-reader-bindingU
subjects:
- kind: User
  name: cloudaware
  namespace: {{ .Release.Namespace | quote }}
  apiGroup: ""
roleRef:
  kind: ClusterRole
  name: cloudaware-node-readerU
  apiGroup: ""
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cloudaware-view-bindingU
subjects:
- kind: User
  name: cloudawareU
  namespace: {{ .Release.Namespace | quote }}
  apiGroup: ""
roleRef:
  kind: ClusterRole
  name: view
  apiGroup: ""
